version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=post-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - POSTGRES_DB=post-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
